### ISSUE TITLE
rename "Tutorial" to "Tangram Tutorial"

### ISSUE THREAD

**Issue by kkowalsky** [tangrams/tangram-play#645]

**Comment by kkowalsky** [comment]
rename to be 'New to Tangram?' in tangram play

**Comment by kkowalsky** [comment]
okay so it looks like the React error @meetar faced is fixed, so once @rmglennon edits the intro tutorial, we can a few of the new tutorials in?

**Comment by meetar** [comment]
@kkowalsky Was there a fix somewhere? I'm still seeing (what I believe is) the error at https://precog.mapzen.com/mapzen/documentation/meetar/tutorial-divs/documentation/tangram/custom-styles/ – do we need to update something?

**Comment by kkowalsky** [comment]
hmmmm @louh said the react error was solved?

**Comment by meetar** [comment]
sweet! do you have a link to it?

**Comment by louh** [comment]
Oh, let me clarify! The React error was being thrown because it was attempting to display _another_ error message in an error modal (which is a React component). These modals aren't present in the embedded version of Play, since I've stripped out all non-essential components, so when the app tells React to display the error, there's no component to display it in, so React threw the error.

I've fixed the _React_ issue by making it so errors are no longer dependent on the React component existing, but it doesn't solve the _original_ problem which is that an error message was being thrown somewhere. Now, the errors you see in console should be the original errors, and not the React one.

Some more details about those errors are here: https://github.com/tangrams/tangram-play/issues/628

The problem is while those errors are being thrown in Tangram Play, they seem to indicate a _potential nonexistence of supposedly omnipresent global browser objects_, which is an existential crisis I've never seen as a browser error before.

**Comment by kkowalsky** [comment]
For the initial release, let's remove the 'tutorial' button and add them in after redesign of the docs.

**Comment by kkowalsky** [comment]
I think we should remove tutorials completely at the moment because it's never been edited and may not be the best teaching tool for Tangram. It also could be confusing to have 'tutorial' where someone might expect that to be a Tangram Play interface tutorial.

**Comment by louh** [comment]
OK - I will rename this issue and assign to you to keep an eye on post-launch
